#!/usr/bin/env perl

use strict;
use warnings;
use Cwd 'getcwd';

use Data::Dumper;

$ENV{"PATH"} = "$ENV{WORK_DIR}/rex/bin:" . $ENV{PATH};
$ENV{"PERLLIB"} = "$ENV{WORK_DIR}/rex/lib:" . (exists $ENV{PERLLIB} ? $ENV{PERLLIB} : "");
$ENV{"PERL5LIB"} = "$ENV{WORK_DIR}/rex/lib:" . (exists $ENV{PERL5LIB} ? $ENV{PERL5LIB} : "");

for my $file (@ARGV) {
  my @out = `perl $ENV{WORK_DIR}/rex/bin/rex -qw -Ff $file test`;
  my @test_line;
  for my $line (@out) {
    chomp $line;

    if($line =~ m/^(ok|not)/) {
      push @test_line, $line;
    }
  }

  print join("\n", @test_line);

  print "\n1.." . scalar(@test_line) . "\n";
}
